name: Assign Squad Label
on:
  issues:
    types:
      - assigned
jobs:
    assign-squad-label:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - uses: actions/setup-node@v1
              with:
                node-version: "16.12.0"
            - name: Get assignees
              id: get-assignees
              uses: actions/github-script@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const assignees = context.payload.issue.assignees.map(assignee => assignee.login)
                      console.log({assignees})
                      
                      return assignees
            - name: Add labels
              id: add-labels
              env:
                GITHUB_AUTH: ${{secrets.GITHUB_TOKEN}}
              with:
                assignees: ${{ steps.get-assignees.outputs.assignees }}
                repo_token: ${{ secrets.GITHUB_TOKEN }}
              run: |
                node ${GITHUB_WORKSPACE}/.github/workflows/assignSquadLabel