name: Update issue squad labels
on:
  issues:
    types:
      - assigned
      - unassigned
jobs:
    update-issue-squad-labels:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                node-version: "16.12.0"
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: |
                  ~/.npm
                  ~/.cache
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-build-${{ env.cache-name }}-
                  ${{ runner.os }}-build-
                  ${{ runner.os }}-
            - run: npm ci
            - name: Update issue labels
              id: update-issue-labels
              env:
                GITHUB_AUTH: ${{secrets.GITHUB_TOKEN}}
              run: node ${GITHUB_WORKSPACE}/.github/workflows/updateIssueSquadLabels